# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: simplebank-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: macos-latest
    steps:
    - name: Checkout SimpleBank directory
      uses: actions/checkout@v3
        
    - name: Change directory to SimpleBank
      run: |
        pwd
        cd simplebank
        pwd
        ls -lR

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check if Makefile exists
      run: |
        pwd
        if [ ! -f Makefile ]; then
          echo "Makefile doesn't exist"
          exit 1
        fi

    - name: Test
      run: make test
